// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RiArticleLine: typeof import('virtual:vite-icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('virtual:vite-icons/ri/bookmark-line')['default']
    RiLightbulbLine: typeof import('virtual:vite-icons/ri/lightbulb-line')['default']
    RiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    RiStickyNoteLine: typeof import('virtual:vite-icons/ri/sticky-note-line')['default']
    RiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    UilGithubAlt: typeof import('virtual:vite-icons/uil/github-alt')['default']
  }
}

export { }
